# $Id$
#   
# PyGEOS distutils setup script
#
# Copyright 2004 Sean Gillies, sgillies@frii.com
#
# This is free software; you can redistribute and/or modify it under
# the terms of the GNU Lesser General Public Licence as published
# by the Free Software Foundation. 
# See the COPYING file for more information.
#
# ===========================================================================
#
# Test before installation
#
# $ python setup.py build
# $ python tests/runtests.py -v
# $ sudo python setup.py install
#
# ===========================================================================

from distutils.core import setup, Extension
import sys

# the extension module, source was generated by SWIG from geos.i
#
# Note that until geos is ready to be installed, we're linking against
# the pre-installed library in source/geom/.libs.

if sys.platform=='win32':
    extmod = Extension('_geos', ['geos_wrap.cxx'],
                       include_dirs = ['../../source/headers',
                                       '../../source/headers/geos'],
                       libraries = ['geos'],
                       library_dirs=['../../source'],)

else:
    extmod = Extension('_geos', ['geos_wrap.cxx'],
                       include_dirs = ['../../source/headers',
                                       '../../source/headers/geos'],
                       libraries = ['stdc++'],
                       extra_objects = ['../../source/geom/.libs/libgeos.a'])

# the python module, generated by SWIG from geos.i
pymod = 'geos'

# The setup function
setup(name = 'PyGEOS',
      version = '2.1.1',
      description = 'Python SWIG interface for GEOS',
      url='http://geos.refractions.net',
      ext_modules = [extmod],
      py_modules = [pymod])

