CXXFLAGS += -g -I../source/headers
#CXXFLAGS += -D__USE_MALLOC
LDFLAGS = -L../source/geom/.libs -lgeos

# g++ -o test6 -g test6.cpp -I/extra/geos/include/geos -L/extra/geos/lib -lgeos
# g++ -g test6.cpp -I/usr/local/include/geos -lgeos ; valgrind --leak-check=yes

all: example 

example: example.cpp

