.\"                                      Hey, EMACS: -*- nroff -*-
.TH GEOS 1 "November  8, 2004"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
geos-config - script to get information about the installed version of GEOS
.SH SYNOPSIS
.B geos-config
[\-\-prefix\fI[=DIR]\fP] [\-\-version] [\-\-libs] [\-\-cflags] [\-\-includes] [\-\-jtsport]
.br
.SH DESCRIPTION
.PP
\fIgeos-config\fP is a tool that is used to configure to determine
the compiler and linker flags that should be used to compile
and link programs that use \fIGEOS\fP. It is also used internally
to the .m4 macros for GNU autoconf that are included with \fIGEOS\fP.
.
\fIGEOS (Geometry Engine - Open Source)\fP is a C++ port of the 
\fIJava Topology Suite (JTS)\fP. As such, it aims to contain the 
complete functionality of JTS in C++. This includes all the 
\fIOpenGIS "Simple Features for SQL"\fP spatial predicate functions 
and spatial operators, as well as specific JTS topology 
functions such as IsValid().
.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
.l
\fIgeos-config\fP accepts the following options:
.TP 8
.B  \-\-version
Print the currently installed version of \fIGEOS\fP on the standard output.
.TP 8
.B  \-\-libs
Print the linker flags that are necessary to link a \fIGEOS\fP program.
.TP 8
.B  \-\-cflags
Print the compiler flags that are necessary to compile a \fIGEOS\fP program.
.TP 8
.B  \-\-prefix=PREFIX
If specified, use PREFIX instead of the installation prefix that \fIGEOS\fP
was built with when computing the output for the \-\-cflags and
\-\-libs options. This option must be specified before any 
\-\-libs or \-\-cflags options.
.TP 8
.B \-\-jtsport
Print the version of Java Topology Suite library, which is implemented 
by the current \fIGEOS\fP library.

.SH SEE ALSO
.BR /usr/share/doc/libgeos-doc/html/index.html
.br
The installed \fIGEOS\fP library is fully documented in the GEOS documentation 
package, at 
.IR /usr/share/doc/libgeos-doc/html/index.html
and the pages at the same location, viewable with a web browser.
.
For further information, see the \fIGEOS\fP home page, at 
http://geos.osgeo.org/.
.SH AUTHOR
See /usr/share/doc/libgeos/AUTHORS
.PP
This manual page was written by Alex Bodnaru <alexbodn@012.net.il>,
for the Debian project (but may be used by others).
