#!/bin/sh

if test "x${1}" = "x"; then
	echo "Usage: $0 <classname>" >&2
	exit 1
fi

classname="${1}"

# TODO: skip directory-only matches
find . -name '*.h' -o -name '*.inl' -o -name '*.cpp' | grep -i "${classname}"
